/*
 * ProductOrdering
 * Please add description
 *
 * OpenAPI spec version: 0.1.0_inProgress
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.atos.ojo.model.lizard;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * An identified part of the order. A product order is decomposed into one or
 * more order items.
 */
@Schema(description = "An identified part of the order. A product order is decomposed into one or more order items.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-13T15:28:56.741+02:00[Africa/Cairo]")
public class ProductOrderItem {
	@JsonProperty("id")
	private String id = null;

	@JsonProperty("action")
	private OrderItemActionType action = null;

	@JsonProperty("@type")
	private String type = null;

	@JsonProperty("product")
	private ProductRefOrValue product = null;

	@JsonProperty("productOffering")
	private ProductOfferingRef productOffering = null;

	@JsonProperty("productOrderItemRelationship")
	private List<OrderItemRelationship> productOrderItemRelationship = null;

	public ProductOrderItem() {
		super();
		// TODO Auto-generated constructor stub
	}

	public ProductOrderItem(String id, OrderItemActionType action, String type, ProductRefOrValue product,
			ProductOfferingRef productOffering, List<OrderItemRelationship> productOrderItemRelationship) {
		super();
		this.id = id;
		this.action = action;
		this.type = type;
		this.product = product;
		this.productOffering = productOffering;
		this.productOrderItemRelationship = productOrderItemRelationship;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public OrderItemActionType getAction() {
		return action;
	}

	public void setAction(OrderItemActionType action) {
		this.action = action;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public ProductRefOrValue getProduct() {
		return product;
	}

	public void setProduct(ProductRefOrValue product) {
		this.product = product;
	}

	public ProductOfferingRef getProductOffering() {
		return productOffering;
	}

	public void setProductOffering(ProductOfferingRef productOffering) {
		this.productOffering = productOffering;
	}

	public List<OrderItemRelationship> getProductOrderItemRelationship() {
		return productOrderItemRelationship;
	}

	public void setProductOrderItemRelationship(List<OrderItemRelationship> productOrderItemRelationship) {
		this.productOrderItemRelationship = productOrderItemRelationship;
	}

}
